# Generated by Django 5.1.6 on 2025-05-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_user_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
