# Generated by Django 5.1.6 on 2025-05-15 16:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_calendarevent_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
